// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vmecanismo_flipping_flipflop.h for the primary calling header

#include "Vmecanismo_flipping_flipflop__pch.h"
#include "Vmecanismo_flipping_flipflop__Syms.h"
#include "Vmecanismo_flipping_flipflop___024root.h"

#ifdef VL_DEBUG
VL_ATTR_COLD void Vmecanismo_flipping_flipflop___024root___dump_triggers__stl(Vmecanismo_flipping_flipflop___024root* vlSelf);
#endif  // VL_DEBUG

VL_ATTR_COLD void Vmecanismo_flipping_flipflop___024root___eval_triggers__stl(Vmecanismo_flipping_flipflop___024root* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vmecanismo_flipping_flipflop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vmecanismo_flipping_flipflop___024root___eval_triggers__stl\n"); );
    // Body
    vlSelf->__VstlTriggered.set(0U, (IData)(vlSelf->__VstlFirstIteration));
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vmecanismo_flipping_flipflop___024root___dump_triggers__stl(vlSelf);
    }
#endif
}

void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__0__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__1__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__2__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__3__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__4__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__5__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__6__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__7__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__8__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__9__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__10__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__11__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__12__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__13__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__14__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
void Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__15__KET____DOT__u0__0(Vmecanismo_flipping_flipflop_mecanismo_flipping_uno* vlSelf);
VL_ATTR_COLD void Vmecanismo_flipping_flipflop___024root___stl_sequent__TOP__0(Vmecanismo_flipping_flipflop___024root* vlSelf);

VL_ATTR_COLD void Vmecanismo_flipping_flipflop___024root___eval_stl(Vmecanismo_flipping_flipflop___024root* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vmecanismo_flipping_flipflop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vmecanismo_flipping_flipflop___024root___eval_stl\n"); );
    // Body
    if ((1ULL & vlSelf->__VstlTriggered.word(0U))) {
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__0__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__0__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__1__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__1__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__2__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__2__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__3__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__3__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__4__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__4__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__5__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__5__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__6__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__6__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__7__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__7__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__8__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__8__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__9__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__9__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__10__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__10__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__11__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__11__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__12__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__12__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__13__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__13__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__14__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__14__KET____DOT__u0));
        Vmecanismo_flipping_flipflop_mecanismo_flipping_uno___nba_sequent__TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__15__KET____DOT__u0__0((&vlSymsp->TOP__mecanismo_flipping_flipflop__DOT__u2__DOT__genblk1__BRA__15__KET____DOT__u0));
        Vmecanismo_flipping_flipflop___024root___stl_sequent__TOP__0(vlSelf);
    }
}
